### PR TITLE
Refactor category page summary data

### PR DESCRIPTION
**Pull request by timciep**
Previously, the `review/helper` block was rewritten, to pull the TurnTo rating for the product.  This means a MySQL query for each product on a category page.

For better efficiency, I have rewritten the `review/review` model's `appendSummary()` function, which pulls the review data for the product collection, on each category page.

This way, native block functionality can be maintained, a single MySQL query is executed, and the `catalog/product` model no longer needs to be rewritten.

### CODE REVIEW

**Comment by timciep** [comment]
Reduction in MySQL usage, in a production environment.  See blue:
image

**Comment by LordZardeck** [comment]
@timciep Thank you for your contribution, I'll take a look into it.

**Comment by timciep** [comment]
@LordZardeck Apologize for jumping the gun with this PR, it seems that my change has caused an issue with sorting category pages by "Top Rated".

Please hold off on reviewing, I should have a fix for this coming soon.

**Comment by timciep** [comment]
@LordZardeck  Sorry about that.  I have resolved the issue that I mentioned and this PR ready for review.

**Comment by LordZardeck** [comment]
@timciep It seems that by removing the original preference, this breaks integration with native reviews display on PDPs. Currently determining if this is an acceptable backwards-breaking change. I will get back to you when I have an decision.

**Comment by LordZardeck** [comment]
Thanks @timciep for your contribution. We will release this in v4.0.0

**Comment by LordZardeck** [comment]
@timciep we have created a `release/4.0.0` branch, can you verify this works for you? We are preparing to release 4.0.0 with these changes

**Comment by timciep** [comment]
Hi @LordZardeck 

I have taken a look at `release/4.0.0` and it works for me.

**Pull request merged**
